name: Check Directory Structure

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check_structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for unexpected files
        run: |
          if find . -name ".DS_Store" | grep -q ".DS_Store"; then
            echo "Error: .DS_Store files should not be committed."
            exit 1
          fi

      - name: Verify required directories and files
        run: |
          REQUIRED=("src" "README.md" "package.json")
          for ITEM in "${REQUIRED[@]}"; do
            if [ ! -e "$ITEM" ]; then
              echo "Error: Required item '$ITEM' is missing."
              exit 1
            fi
          done
